"""Small deterministic helpers shared by extractors."""

from __future__ import annotations

from pathlib import Path
import re
from typing import Iterable


SOURCE_SUFFIXES = {".c", ".cc", ".cpp", ".cxx", ".m", ".mm"}
HEADER_SUFFIXES = {".h", ".hh", ".hpp", ".hxx", ".inc"}
C_CPP_SUFFIXES = SOURCE_SUFFIXES | HEADER_SUFFIXES
DOCUMENTATION_SUFFIXES = {".md", ".markdown", ".rst", ".txt"}
DOCUMENTATION_FILENAMES = {"README", "README.md", "README.rst", "README.txt"}

LANGUAGE_BY_SUFFIX = {
    ".c": "c",
    ".h": "c-header",
    ".cc": "c++",
    ".cpp": "c++",
    ".cxx": "c++",
    ".hh": "c++-header",
    ".hpp": "c++-header",
    ".hxx": "c++-header",
    ".inc": "c/c++-include",
    ".m": "objective-c",
    ".mm": "objective-c++",
    ".md": "markdown",
    ".markdown": "markdown",
    ".rst": "restructuredtext",
    ".txt": "text",
}

BUILD_FILE_NAMES = {
    "CMakeLists.txt",
    "Makefile",
    "meson.build",
    "configure",
    "compile_commands.json",
    "build.ninja",
}

GENERATED_MARKERS = {
    "generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
}

SKIP_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "dist",
}


def posix_relpath(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def line_number_for_offset(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def classify_language(path: Path) -> str:
    return LANGUAGE_BY_SUFFIX.get(path.suffix.lower(), "unknown")


def is_c_cpp(path: Path) -> bool:
    return path.suffix.lower() in C_CPP_SUFFIXES


def is_source(path: Path) -> bool:
    return path.suffix.lower() in SOURCE_SUFFIXES


def is_header(path: Path) -> bool:
    return path.suffix.lower() in HEADER_SUFFIXES


def is_documentation(path: Path) -> bool:
    return path.name in DOCUMENTATION_FILENAMES or path.suffix.lower() in DOCUMENTATION_SUFFIXES


def iter_repo_files(root: Path) -> Iterable[Path]:
    for path in sorted(root.rglob("*")):
        if any(part in SKIP_DIR_NAMES for part in path.relative_to(root).parts[:-1]):
            continue
        if path.is_file():
            yield path


def detect_generated(text: str) -> bool:
    head = text[:2048].lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def strip_comments_preserve_lines(text: str) -> str:
    def block_replacer(match: re.Match[str]) -> str:
        return "\n" * match.group(0).count("\n")

    text = re.sub(r"/\*.*?\*/", block_replacer, text, flags=re.DOTALL)
    text = re.sub(r"//.*", "", text)
    return text


def code_line(text: str, line: int) -> str:
    lines = text.splitlines()
    if 1 <= line <= len(lines):
        return lines[line - 1].strip()
    return ""
